import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/navbar';
import { ScrollArea } from '@/components/ui/scroll-area';
import SignIn from '@/components/modal/sign-in';

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VaViVu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased flex min-h-screen w-full flex-col`}
      >
        <Navbar />
        <main>
          <ScrollArea className="h-[calc(100vh-64px)]">{children}</ScrollArea>
          <SignIn />
        </main>
      </body>
    </html>
  );
}
